import { Customer, Machine, AvailableMachine, Vehicle } from '../types';

export const mockCustomers: Customer[] = [
  {
    _id: 'C001',
    name: 'BuildCorp Construction',
    email: 'info@buildcorp.com',
    phone: '+1234567890',
    businessType: 'Construction',
    workCategory: 'General Contractor',
    address: '123 Main St, Building City, ST 12345',
    contactPerson: 'John Smith',
    emergencyContact: '+1234567891',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Bulldozer', 'Loader'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Wednesday', 'Friday'],
      averageRentalDuration: 3,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 1250,
    totalRentals: 45,
    totalSpent: 28750,
    createdAt: '2024-01-01T00:00:00.000Z'
  },
  {
    _id: 'C002',
    name: 'Metro Infrastructure',
    email: 'contact@metroinfra.com',
    phone: '+1234567892',
    businessType: 'Infrastructure',
    workCategory: 'Road Construction',
    address: '456 Oak Ave, Metro City, ST 12346',
    contactPerson: 'Sarah Johnson',
    emergencyContact: '+1234567893',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Grader'],
    rentalUsagePatterns: {
      peakTimes: ['Tuesday', 'Thursday'],
      averageRentalDuration: 2,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 0,
    totalRentals: 28,
    totalSpent: 18200,
    createdAt: '2024-01-02T00:00:00.000Z'
  },
  {
    _id: 'C003',
    name: 'Skyline Developers',
    email: 'info@skyline.dev',
    phone: '+1234567894',
    businessType: 'Development',
    workCategory: 'Commercial Developer',
    address: '789 Pine St, Skyline City, ST 12347',
    contactPerson: 'Mike Rodriguez',
    emergencyContact: '+1234567895',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Bulldozer', 'Crane'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      averageRentalDuration: 5,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 3200,
    totalRentals: 67,
    totalSpent: 45600,
    createdAt: '2024-01-03T00:00:00.000Z'
  },
  {
    _id: 'C004',
    name: 'Urban Projects Ltd',
    email: 'projects@urban.com',
    phone: '+1234567896',
    businessType: 'Urban Development',
    workCategory: 'City Planning',
    address: '321 Elm Rd, Urban City, ST 12348',
    contactPerson: 'Lisa Chen',
    emergencyContact: '+1234567897',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Mini Excavator'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Friday'],
      averageRentalDuration: 4,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 800,
    totalRentals: 34,
    totalSpent: 21800,
    createdAt: '2024-01-04T00:00:00.000Z'
  },
  {
    _id: 'C005',
    name: 'Coastal Construction',
    email: 'build@coastal.com',
    phone: '+1234567898',
    businessType: 'Construction',
    workCategory: 'Marine Construction',
    address: '654 Maple Dr, Coastal Town, ST 12349',
    contactPerson: 'David Wilson',
    emergencyContact: '+1234567899',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Bulldozer', 'Generator'],
    rentalUsagePatterns: {
      peakTimes: ['Tuesday', 'Wednesday', 'Thursday'],
      averageRentalDuration: 3,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 0,
    totalRentals: 23,
    totalSpent: 14200,
    createdAt: '2024-01-05T00:00:00.000Z'
  },
  {
    _id: 'C006',
    name: 'Highway Builders Inc',
    email: 'info@highwaybuilders.com',
    phone: '+1234567900',
    businessType: 'Infrastructure',
    workCategory: 'Highway Construction',
    address: '987 Highway Blvd, Road City, ST 12350',
    contactPerson: 'Robert Brown',
    emergencyContact: '+1234567901',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Bulldozer', 'Grader'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Tuesday', 'Wednesday'],
      averageRentalDuration: 6,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 1850,
    totalRentals: 52,
    totalSpent: 32400,
    createdAt: '2024-01-06T00:00:00.000Z'
  },
  {
    _id: 'C007',
    name: 'Mining Solutions Ltd',
    email: 'contact@miningsolutions.com',
    phone: '+1234567902',
    businessType: 'Mining',
    workCategory: 'Surface Mining',
    address: '456 Mine Rd, Mining Town, ST 12351',
    contactPerson: 'Jennifer Davis',
    emergencyContact: '+1234567903',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Excavator', 'Bulldozer', 'Loader'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      averageRentalDuration: 7,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 4200,
    totalRentals: 89,
    totalSpent: 56700,
    createdAt: '2024-01-07T00:00:00.000Z'
  },
  {
    _id: 'C008',
    name: 'Residential Developers',
    email: 'info@residential.dev',
    phone: '+1234567904',
    businessType: 'Development',
    workCategory: 'Residential Developer',
    address: '789 Home St, Residential City, ST 12352',
    contactPerson: 'Michael Wilson',
    emergencyContact: '+1234567905',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Mini Excavator', 'Generator'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Wednesday', 'Friday'],
      averageRentalDuration: 2,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 650,
    totalRentals: 31,
    totalSpent: 18900,
    createdAt: '2024-01-08T00:00:00.000Z'
  },
  {
    _id: 'C009',
    name: 'Industrial Contractors',
    email: 'contractors@industrial.com',
    phone: '+1234567906',
    businessType: 'Industrial',
    workCategory: 'Industrial Construction',
    address: '321 Factory Ave, Industrial City, ST 12353',
    contactPerson: 'Amanda Taylor',
    emergencyContact: '+1234567907',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Crane', 'Excavator', 'Bulldozer'],
    rentalUsagePatterns: {
      peakTimes: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      averageRentalDuration: 8,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 0,
    totalRentals: 76,
    totalSpent: 48900,
    createdAt: '2024-01-09T00:00:00.000Z'
  },
  {
    _id: 'C010',
    name: 'Landscape Architects',
    email: 'info@landscapearch.com',
    phone: '+1234567908',
    businessType: 'Landscaping',
    workCategory: 'Landscape Design',
    address: '654 Garden St, Landscape City, ST 12354',
    contactPerson: 'Christopher Lee',
    emergencyContact: '+1234567909',
    dealerId: 'D001',
    rentalHistory: [],
    frequentlyRentedMachines: ['Mini Excavator', 'Loader'],
    rentalUsagePatterns: {
      peakTimes: ['Tuesday', 'Thursday'],
      averageRentalDuration: 1,
      preferredRentalDays: ['Weekdays']
    },
    outstandingDues: 1200,
    totalRentals: 18,
    totalSpent: 11200,
    createdAt: '2024-01-10T00:00:00.000Z'
  }
];

export const mockVehicles: Vehicle[] = [
  {
    _id: '1',
    vehicleId: 'EXC-001',
    type: 'Excavator',
    model: 'CAT 320D',
    condition: 'good',
    status: 'rented',
    dealerId: 'dealer1',
    currentRentalId: null,
    expectedReturnDate: '2024-01-25',
    checkOutTime: '2024-01-20T08:30:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-10',
    nextMaintenanceDate: '2024-02-10',
    totalRentals: 67,
    totalRevenue: 33500,
    fuelType: 'diesel',
    engineHoursPerDay: 1.5,
    operatingDays: 15,
    carbonEmissionPerDay: 4.74,
    totalCarbonEmission: 71.1,
    specifications: {
      weight: '20 tons',
      engine: 'CAT C7.1',
      bucketCapacity: '1.2 m³',
      maxDigDepth: '6.5 m'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '2',
    vehicleId: 'BUL-001',
    type: 'Bulldozer',
    model: 'CAT D6T',
    condition: 'good',
    status: 'rented',
    dealerId: 'dealer1',
    currentRentalId: null,
    expectedReturnDate: '2024-01-22',
    checkOutTime: '2024-01-19T09:15:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-08',
    nextMaintenanceDate: '2024-02-08',
    totalRentals: 54,
    totalRevenue: 27000,
    fuelType: 'diesel',
    engineHoursPerDay: 7.5,
    operatingDays: 25,
    carbonEmissionPerDay: 23.7,
    totalCarbonEmission: 592.5,
    specifications: {
      weight: '18 tons',
      engine: 'CAT C9.3',
      bladeWidth: '3.2 m',
      maxSpeed: '12 km/h'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '3',
    vehicleId: 'EXC-002',
    type: 'Excavator',
    model: 'CAT 330D',
    condition: 'good',
    status: 'rented',
    dealerId: 'dealer1',
    currentRentalId: null,
    expectedReturnDate: '2024-01-28',
    checkOutTime: '2024-01-21T07:45:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-12',
    nextMaintenanceDate: '2024-02-12',
    totalRentals: 42,
    totalRevenue: 21000,
    fuelType: 'diesel',
    engineHoursPerDay: 5,
    operatingDays: 20,
    carbonEmissionPerDay: 15.8,
    totalCarbonEmission: 316.0,
    specifications: {
      weight: '30 tons',
      engine: 'CAT C9.3',
      bucketCapacity: '1.8 m³',
      maxDigDepth: '8.2 m'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '4',
    vehicleId: 'CRN-001',
    type: 'Crane',
    model: 'Liebherr LTM 1100',
    condition: 'under repair',
    status: 'under maintenance',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-15T14:20:00.000Z',
    maintenanceStatus: 'under repair',
    lastMaintenanceDate: '2024-01-05',
    nextMaintenanceDate: '2024-02-05',
    totalRentals: 38,
    totalRevenue: 19000,
    fuelType: 'diesel',
    engineHoursPerDay: 0,
    operatingDays: 20,
    carbonEmissionPerDay: 0.0,
    totalCarbonEmission: 0.0,
    specifications: {
      weight: '48 tons',
      engine: 'Mercedes-Benz OM 906 LA',
      maxLiftCapacity: '100 tons',
      maxBoomLength: '60 m'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '5',
    vehicleId: 'LDR-001',
    type: 'Loader',
    model: 'CAT 950H',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-22T16:30:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-15',
    nextMaintenanceDate: '2024-02-15',
    totalRentals: 51,
    totalRevenue: 25500,
    fuelType: 'diesel',
    engineHoursPerDay: 6,
    operatingDays: 10,
    carbonEmissionPerDay: 18.96,
    totalCarbonEmission: 189.6,
    specifications: {
      weight: '16 tons',
      engine: 'CAT C9.3',
      bucketCapacity: '3.2 m³',
      maxSpeed: '35 km/h'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '6',
    vehicleId: 'GRD-001',
    type: 'Grader',
    model: 'CAT 140K',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-23T10:00:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-18',
    nextMaintenanceDate: '2024-02-18',
    totalRentals: 33,
    totalRevenue: 16500,
    fuelType: 'diesel',
    engineHoursPerDay: 4,
    operatingDays: 12,
    carbonEmissionPerDay: 12.64,
    totalCarbonEmission: 151.68,
    specifications: {
      weight: '14 tons',
      engine: 'CAT C6.6',
      bladeWidth: '4.2 m',
      maxSpeed: '40 km/h'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '7',
    vehicleId: 'TRK-001',
    type: 'Dump Truck',
    model: 'CAT 730',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-24T11:30:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-20',
    nextMaintenanceDate: '2024-02-20',
    totalRentals: 45,
    totalRevenue: 22500,
    fuelType: 'diesel',
    engineHoursPerDay: 8,
    operatingDays: 18,
    carbonEmissionPerDay: 25.28,
    totalCarbonEmission: 455.04,
    specifications: {
      weight: '25 tons',
      engine: 'CAT C11',
      payloadCapacity: '15 tons',
      maxSpeed: '45 km/h'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '8',
    vehicleId: 'EXC-003',
    type: 'Mini Excavator',
    model: 'CAT 301.8',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-25T09:15:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-22',
    nextMaintenanceDate: '2024-02-22',
    totalRentals: 28,
    totalRevenue: 14000,
    fuelType: 'petrol',
    engineHoursPerDay: 3,
    operatingDays: 8,
    carbonEmissionPerDay: 9.48,
    totalCarbonEmission: 75.84,
    specifications: {
      weight: '1.8 tons',
      engine: 'Kubota D1105',
      bucketCapacity: '0.04 m³',
      maxDigDepth: '2.5 m'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '9',
    vehicleId: 'GEN-001',
    type: 'Generator',
    model: 'CAT C15',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-26T14:45:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-25',
    nextMaintenanceDate: '2024-02-25',
    totalRentals: 62,
    totalRevenue: 31000,
    fuelType: 'diesel',
    engineHoursPerDay: 12,
    operatingDays: 30,
    carbonEmissionPerDay: 37.92,
    totalCarbonEmission: 1137.6,
    specifications: {
      weight: '2.5 tons',
      engine: 'CAT C15',
      powerOutput: '580 kW',
      fuelCapacity: '400L'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '10',
    vehicleId: 'WLD-001',
    type: 'Welding Machine',
    model: 'Lincoln Vantage 500',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-27T08:00:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-26',
    nextMaintenanceDate: '2024-02-26',
    totalRentals: 35,
    totalRevenue: 17500,
    fuelType: 'diesel',
    engineHoursPerDay: 6,
    operatingDays: 14,
    carbonEmissionPerDay: 18.96,
    totalCarbonEmission: 265.44,
    specifications: {
      weight: '0.8 tons',
      engine: 'Kubota D1105',
      weldingOutput: '500A',
      fuelCapacity: '25L'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '11',
    vehicleId: 'COMP-001',
    type: 'Compressor',
    model: 'Atlas Copco XAS 185',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-28T12:30:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-27',
    nextMaintenanceDate: '2024-02-27',
    totalRentals: 41,
    totalRevenue: 20500,
    fuelType: 'petrol',
    engineHoursPerDay: 4,
    operatingDays: 16,
    carbonEmissionPerDay: 12.64,
    totalCarbonEmission: 202.24,
    specifications: {
      weight: '0.4 tons',
      engine: 'Honda GX390',
      airOutput: '185 cfm',
      fuelCapacity: '15L'
    },
    createdAt: '2024-01-01'
  },
  {
    _id: '12',
    vehicleId: 'LIFT-001',
    type: 'Forklift',
    model: 'Toyota 8FGCU25',
    condition: 'good',
    status: 'available',
    dealerId: 'dealer1',
    currentRentalId: null,
    checkInTime: '2024-01-29T10:15:00.000Z',
    maintenanceStatus: 'operational',
    lastMaintenanceDate: '2024-01-28',
    nextMaintenanceDate: '2024-02-28',
    totalRentals: 48,
    totalRevenue: 24000,
    fuelType: 'EV',
    engineHoursPerDay: 5,
    operatingDays: 22,
    carbonEmissionPerDay: 0,
    totalCarbonEmission: 0,
    specifications: {
      weight: '3.2 tons',
      engine: 'Electric Motor',
      liftCapacity: '2.5 tons',
      maxLiftHeight: '6.5 m'
    },
    createdAt: '2024-01-01'
  }
];

export const mockMachines: Machine[] = [
  {
    id: 'M001',
    type: 'Excavator',
    customerId: 'C001',
    customerName: 'BuildCorp Construction',
    site: 'Downtown Project',
    checkIn: '2024-01-15',
    condition: 'Good',
    runtime: 120,
    idleTime: 30,
    fuelUsed: 45,
    co2Emitted: 120,
    returnDue: '2024-01-20'
  },
  {
    id: 'M002',
    type: 'Bulldozer',
    customerId: 'C002',
    customerName: 'Metro Infrastructure',
    site: 'Highway Extension',
    checkIn: '2024-01-16',
    condition: 'Needs Maintenance',
    runtime: 95,
    idleTime: 45,
    fuelUsed: 38,
    co2Emitted: 95,
    returnDue: '2024-01-22'
  },
  {
    id: 'M003',
    type: 'Excavator',
    customerId: 'C003',
    customerName: 'Skyline Developers',
    site: 'Office Complex',
    checkIn: '2024-01-17',
    condition: 'Good',
    runtime: 150,
    idleTime: 20,
    fuelUsed: 55,
    co2Emitted: 140,
    returnDue: '2024-01-25'
  }
];

export const mockAvailableMachines: AvailableMachine[] = [
  {
    id: 'AM001',
    type: 'Excavator',
    location: 'Main Yard',
    status: 'Available'
  },
  {
    id: 'AM002',
    type: 'Bulldozer',
    location: 'Main Yard',
    status: 'Available'
  },
  {
    id: 'AM003',
    type: 'Crane',
    location: 'Main Yard',
    status: 'Maintenance'
  }
];